# BCI Competition IV 2b - LOSO 配置
name: bci2b    # 用于文件夹命名

_target_: src.data.loso_datamodule.LOSODataModule
dataset_name: "BNCI2014_004"
all_subject_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9]
n_folds: 3
fold_id: 1
n_classes: 2                  # 2b 只有 2 类
tmin: 0.0
tmax: 4.0
fmin: 4.0
fmax: 38.0
batch_size: 128
num_workers: 8
pin_memory: true
persistent_workers: true
seed: ${seed}
data_dir: "./data"
show_fold_info: true